### ISSUE TITLE
Memory leak there should not have memory leak

### ISSUE THREAD

**Issue by rrezino** [VSoftTechnologies/Delphi-Mocks#110]
Whe I turn on the memoryleak watcher, all tests are shown with leaked memory, but they shouldn't 
This is the code: 
```
procedure TestTNullJSONMarshal.NullObjectShouldBeNull;
var
  r: String;
begin
  r := '{"someObject":null}';
  Assert.AreEqual(r, '{"someObject":null}');
end;
```
I didn't create any objects, just used the "string". 
This is the result: 

![leak](https://cloud.githubusercontent.com/assets/19705449/22828592/6aa9bf38-ef9e-11e6-8dc1-8b9afc51c2d4.png)

**Comment by sglienke** [comment]
Problem is that the leak monitor is stupid and just compares used memory before and after.

If you call any Assert method it goes through some code including the OnAssert handler that was attached in TDUnitX.Create where it uses MonitorEnter/MonitorLeave. If that is executed for the first time on an instance it internally allocates some memory for that monitor stuff. That is only deallocated once the instance gets destroyed. But since it was called on FAssertCounters this will only get destroyed once the application ends and TDUnitX.Destroy runs.

Anyway even if this was fixed (by causing the TMonitor stuff to happen before the first test runs) there is so much code inside the RTL and other places that lazy initialize things that would reported by such naive memleak detection.

Furthermore it just reports numbers of bytes which don't give you much useful information.

I recommend using [LeakCheck](https://bitbucket.org/shadow_cs/delphi-leakcheck) which has a way more detailed reporting and the possibility to register "known" leaks for example those lazy initializations that might happen during a test.

**Comment by vincentparrett** [comment]
Closing this as it's the wrong repo, this is a DUnitX issue.
