### ISSUE TITLE
Creating match any conditions in a WillReturn.When

### ISSUE THREAD

**Issue by mmarquee** [VSoftTechnologies/Delphi-Mocks#61]
Hi,

Not sure how to ask questions, but I want to be able to deal with any parameters in the following mocking setup.

mock.Setup.WillReturn(TValue.From(true)).When.DoIt(param1, param2);

Is there a way of doing this ?

**Comment by staticcat** [comment]
/tldr
Short answer, no.  

Long answer, I wish it could be.

/explanation /rant
I really wanted to implement this feature. However as Delphi's parameter calling is undefined behaviour, I couldn't. 

The goal syntax was the following, and can be seen in f-param-matches branch. 

mock.Setup.WillReturn(TValue.From(true)).When.DoIt(Is.Any<integer>(), Is.Any<string>());

As a result development has stalled a bit. I consider this to be a critical feature of a Mocking framework. The only other way I can see it implemented is via using text names of the functions, and procedures passing an array of parameter values. 

mock.Setup.WillReturn(TValue.From(true)).When("DoIt", [Is.Any<integer>(), Is.Any<string>()]);

The problem I have with this is that its not caught at compile time. Tests should break as early as possible. If the interface has changed, then the test should break in compile as it has not been updated. It will still break, but much later when the tests are actually run. 

Another point to this is that maintenance is harder. The IDE knows nothing about the text passed to the When function being an actual function/procedure. So when IDE plugins look for usages of an interface, this test would not appear in that list.  

So, when I or someone else gets some spare time we might implement the text version for starters until we think of something better. Better have a functional framework, rather than it being incomplete. I think the wind was taken out of our sails when we found the undefined behaviour (which we could see no real good reason for).

**Comment by mmarquee** [comment]
Thank you very much for this answer, whilst it doesn't enable me to do what I need to do (yet), it is very detailed and explains the situation properly.

**Comment by staticcat** [comment]
This has been implemented in pr #64. The way I got around the undefined order of parameter execution was to simply define it when the matcher was called. This has lead to It being defined as a function now. 

e.g. 
It(0).IsAny<integer>()

The above example will match the first parameter. This means you could have the following;

e.g.
mock.Setup.WillReturn(8).When.TakesTwoParams(It(0).IsAny<integer>(), It(1).IsEqualTo<boolean>(false));

Note that this means you can still get errors by incorrectly indexing the matches. 

e.g.
mockCredit.Setup.WillReturn(8).When.TakesTwoParams(It(1).IsAny<integer>(), It(0).IsEqualTo<boolean>(false));

If people could work on the param matcher branch and give me some feedback that would be great. If not, might just merge it.

**Comment by staticcat** [comment]
So param matchers have been implemented and merged into master. I am marking this issue resolved.
